
package com.mycompany.coffeemachine;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;


public class MainJFrame extends javax.swing.JFrame {
    CoffeeMachine machine = new CoffeeMachine(20000, 5000);

    ConsoleLogger clLogger = new ConsoleLogger();
    FileLogger fileLogger = new FileLogger("logs.txt");

    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        JFormattedTextField spinnerTextField = ((JSpinner.DefaultEditor) CoffeTypeSpinner.getEditor()).getTextField();
        spinnerTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        CoffeTypeSpinner = new javax.swing.JSpinner();
        GrindLevelTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SizeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        makeCoffeeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        refillBtn = new javax.swing.JButton();
        cleanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Machine");
        setResizable(false);

        CoffeTypeSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"Espresso-Single", "Espresso-Double", "Americano-Single", "Americano-Double"}));
        CoffeTypeSpinner.setEditor(new javax.swing.JSpinner.ListEditor(CoffeTypeSpinner));

        jLabel1.setText("Grind Level");

        jLabel2.setText("Size");

        makeCoffeeBtn.setText("Make Coffee");
        makeCoffeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeCoffeeBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Coffee Type");

        refillBtn.setText("ReFill");
        refillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refillBtnActionPerformed(evt);
            }
        });

        cleanBtn.setText("Clean");
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GrindLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeCoffeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CoffeTypeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cleanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(472, 472, 472))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrindLevelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoffeTypeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(makeCoffeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cleanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(refillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void makeCoffeeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
       

       
       if(GrindLevelTxt.getText().toString().isEmpty() || SizeTxt.getText().toString().isEmpty())
       {
            JOptionPane.showMessageDialog(this, "please specify size and grind level!");
       }
       else{
           
            String coffeType = CoffeTypeSpinner.getValue().toString();
            int grindLevel = Integer.parseInt(GrindLevelTxt.getText().toString());
            int size = Integer.parseInt(SizeTxt.getText().toString());

            try
            {
                Coffeecup cup =   machine.serveCoffee(coffeType, grindLevel, size);
                   
                 JOptionPane.showMessageDialog(this, "Take your Coffee Cup !"
                         + "\n\n"+cup.getInfo()+"\n");
                 
                
                 
                 clLogger.log(cup.getInfo());
                 
                 fileLogger.log(cup.getInfo());
                 
             
                if(machine.isCleaningNeeded())
                {
                    machine.clean();
                }
                if(machine.waterLevel < 200 || machine.beansLevel < 200)
                {
                    try
                    {
                        machine.fillWater(4000);
                        machine.fillBeans(15000);
                    }
                    catch(CoffeExp e)
                    {
                         JOptionPane.showMessageDialog(this, e.toString());
                    }
                }
                

            }
            catch(CoffeExp exp)
            {
                JOptionPane.showMessageDialog(this, exp.toString());
            }           
       }
        

       
       
        
    }                                             

    private void refillBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try
        {
            machine.fillWater(4000);
            machine.fillBeans(15000);
            JOptionPane.showMessageDialog(this, "The coffee machine was filled successfully.");
        }
        catch(CoffeExp e)
        {
             JOptionPane.showMessageDialog(this, e.toString());
        }
    }                                         

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        machine.clean();
                    JOptionPane.showMessageDialog(this, "The coffee machine was cleaned successfully.");

        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
                
              
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JSpinner CoffeTypeSpinner;
    private javax.swing.JTextField GrindLevelTxt;
    private javax.swing.JTextField SizeTxt;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton makeCoffeeBtn;
    private javax.swing.JButton refillBtn;
    // End of variables declaration                   
}
